DROP TABLE IF EXISTS Products;

CREATE TABLE Products (
	ID INT PRIMARY KEY,
	Type ENUM('FOOD', 'TOY', 'ACCESSORY') NOT NULL,
	Price DOUBLE NOT NULL,
	Name VARCHAR(250) NOT NULL,
	Quantity INT NOT NULL,
    Size ENUM('SMALL', 'MEDIUM', 'LARGE') NOT NULL,
	Status ENUM('AVAILABLE', 'NOT AVAILABLE'),
	ImageURL VARCHAR(250)
);

